services:
  # Django Backend
  backend:
    image: jaishankar7655/healthcare-backend:latest
    container_name: healthcare_backend
    restart: always
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-change-in-production
      - ALLOWED_HOSTS=40.81.224.249,localhost,127.0.0.1
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sqlite_data:/app
    networks:
      - healthcare_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  # Patient Portal
  patient-portal:
    image: jaishankar7655/healthcare-patient-portal:latest
    container_name: healthcare_patient_portal
    restart: always
    networks:
      - healthcare_network

  # Admin Portal
  admin-portal:
    image: jaishankar7655/healthcare-admin-portal:latest
    container_name: healthcare_admin_portal
    restart: always
    networks:
      - healthcare_network

  # Doctor Portal
  doctor-portal:
    image: jaishankar7655/healthcare-doctor-portal:latest
    container_name: healthcare_doctor_portal
    restart: always
    networks:
      - healthcare_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: healthcare_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - patient_build:/usr/share/nginx/html/patient
      - admin_build:/usr/share/nginx/html/admin
      - doctor_build:/usr/share/nginx/html/doctor
    depends_on:
      - backend
      - patient-portal
      - admin-portal
      - doctor-portal
    networks:
      - healthcare_network

volumes:
  sqlite_data:
  static_volume:
  media_volume:
  patient_build:
  admin_build:
  doctor_build:


networks:
  healthcare_network:
    driver: bridge
